name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次，你可以根据需要调整频率
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: yimo0871/mangos-wotlk
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config user.name "yimo0871"
        git config user.email "42022883@qq.com"
        git config --global user.email "42022883@qq.com"
        git config --global user.name "yimo0871"

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/cmangos/mangos-wotlk.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout master
        git merge upstream/master --allow-unrelated-histories
        git push origin master
